[package]
name = "mlimage-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lz4_flex = "0.11.3"
ndarray = "0.15.6"
winnow = "0.6.5"
num = "0.4.1"

[dev-dependencies]
hexdump = "0.1.1"
