[package]
name = "mlimage_py"
version = "0.1.0"
edition = "2021"

[lib]
name = "mlimage"
crate-type = ["cdylib"]

[dependencies]
mlimage-rs = { version = "0.1.0", path = "../mlimage_format" }
numpy = "0.21.0"
pyo3 = { version = "0.21.1", features = ["extension-module"] }
